# Controller params
param1: 0.25             # P_xy
param2: 0.001           # I_xy
param3: 0.15            # D_xy
param4: 4.5             # P_z
param5: 0.0015          # I_z
param6: 0.85             # D_z

# Linear Kalman Filter
param7: 0.01            # Q pos
param8: 0.01            # Q vel
param9: 1.0             # Q acc
param10: 1.0            # R pos
param11: 1.0            # R acc

param12: 0.0            # Unused






