#- list of names of dynamically loaded controllers
controllers : [
  "Se3Controller",
  "MpcController",
  "FailsafeController",
  "EmergencyController",
  "Task01Controller",
]

safety:
  tilt_limit:
    eland:
      enabled: false
    disarm:
      enabled: false
    tilt_error_disarm:
      enabled: false

Task01Controller:
  address: "task_01_wrapper/Task01Wrapper"
  namespace: "task_01_wrapper"
  eland_threshold: 0.0 # [m], position error triggering eland
  failsafe_threshold: 0.0 # [m], position error triggering failsafe land
  odometry_innovation_threshold: 0.0 # [m], position odometry innovation threshold
  human_switchable: true

MpcController:
  eland_threshold: 0.0 # [m], position error triggering eland
  failsafe_threshold: 0.0 # [m], position error triggering failsafe land
  odometry_innovation_threshold: 0.0 # [m], position odometry innovation threshold
